using PrincessLegacyEnchantedRealms.clientDataManager;
using PrincessLegacyEnchantedRealms.gameComponents;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

// This file contains hand-written code for the COS20007 module.
// All code was written by Truong Duc Sang and was not generated by any tools or automated code generators.
// This code is intended for use in Princess Legacy: Enchanted Realms and is not to be copied or reused without permission.


namespace PrincessLegacyEnchantedRealms.GachaSystem
{
    public class WishWindow : Form
    {
        private SoundPlayer player;
        private List<Control> _formControls = new List<Control>();
        private Player _player;
        private Label _currentPlayerCurrency;
        private Label _wishPlayerCurrency;
        public WishWindow(Player player, Label currentPlayerCurrency) {
            this.Size = new System.Drawing.Size(1920, 1080);
            this.MaximizeBox= false;
            this.WindowState= FormWindowState.Maximized;
            _player = player;
            _currentPlayerCurrency = currentPlayerCurrency;
            InitializeComponents();
            this.Icon = new Icon("anis.ico");
            this.Text = "Main Form";
            this.FormBorderStyle = FormBorderStyle.None;
            foreach (Control control in Controls)
            {
                _formControls.Add(control);
            }
        }
        private void InitializeComponents()
        {
            // This code uses content from the TV series Breaking Bad as inspiration for the game's gacha system and currency.
            // The content from Breaking Bad is the intellectual property of its creators and is used in this code with respect to their rights.
            // No copyrighted content from Breaking Bad is included in this code, and any similarity to the TV series is purely coincidental.

            this.BackgroundImage = Image.FromFile(@"homePageResources\wish\mainWishEvent.png");
            this.BackgroundImageLayout = ImageLayout.Stretch;

            // Create the picture boxes and add click event handlers
            CustomPictureBox pictureBox1 = new CustomPictureBox(new Size(180, 90), new Point(600, 0), @"homePageResources\wish\wishButton1.png");
            pictureBox1.Click += PictureBox1_Click;
            this.Controls.Add(pictureBox1);

            CustomPictureBox pictureBox2 = new CustomPictureBox(new Size(180, 90), new Point(820, 0), @"homePageResources\wish\wishButton2.png");
            pictureBox2.Click += PictureBox2_Click;
            this.Controls.Add(pictureBox2);

            CustomPictureBox pictureBox3 = new CustomPictureBox(new Size(360, 90), new Point(1020, 780), @"homePageResources\wish\wishButton.png");
            pictureBox3.Click += GachaButton_Click;
            this.Controls.Add(pictureBox3);

            Button detailsButton = new Button();
            detailsButton.Text = "Details";
            detailsButton.Size = new Size(80, 30);
            detailsButton.Location = new Point(50, 800);
            detailsButton.BackColor = Color.FromArgb(244, 243, 239);
            detailsButton.ForeColor = Color.FromArgb(207, 159, 73); //Singature color of TenTen Kakumei website
            detailsButton.Click += DetailsButton_Click;
            this.Controls.Add(detailsButton);

            CustomPictureBox closeButton = new CustomPictureBox(new Size(40, 40), new Point(1480, 0), @"homePageResources\wish\wishCloseButton.png");
            closeButton.Click += CloseButton_Click;
            this.Controls.Add(closeButton);
            //display player's currency
            //display in-game currency icon
            PictureBox bs_icon = new PictureBox();
            bs_icon.Image = Image.FromFile("currencySystems\\bs_icon.png");
            bs_icon.Location = new Point(1205, 15);
            bs_icon.SizeMode = PictureBoxSizeMode.StretchImage;
            bs_icon.BackColor = Color.Transparent;
            bs_icon.Size = new Size(30, 40);
            this.Controls.Add(bs_icon);

            //label to display player's currency
            _wishPlayerCurrency = new Label();
            _wishPlayerCurrency.Location = new Point(1235, 19);
            _wishPlayerCurrency.Font = new Font("Segoe UI", 15);
            _wishPlayerCurrency.BackColor = Color.White;
            _wishPlayerCurrency.Text = _player.GetSetCurrency.ToString();
            this.Controls.Add(_wishPlayerCurrency);
            //display a cover box for readablity
            DrawCoverBox resourcesCover = new DrawCoverBox(new Point(1200, 10), new Size(280, 50), Color.White, this);
            bs_icon.BringToFront();
            _wishPlayerCurrency.BringToFront();

            player = new System.Media.SoundPlayer();
            player.SoundLocation = @"homePageResources\wish\gachaMusic.wav";
            player.PlayLooping();
        }

        private void CloseButton_Click(object sender, EventArgs e)
        {
            player.Stop();
            this.Dispose();
        }

      
        private void PictureBox1_Click(object sender, EventArgs e)
        {
            this.BackgroundImage = Image.FromFile(@"homePageResources\wish\mainWishEvent.png");
        }

        private void PictureBox2_Click(object sender, EventArgs e)
        {
            this.BackgroundImage = Image.FromFile(@"homePageResources\wish\lycorecoEventWish.png");
        }
        private PictureBox gachaAnimation;
        private int pitySystem = 12;
        private async void GachaButton_Click(object sender, EventArgs e)
        {
            if (_player.GetSetCurrency < 1600)
            {
                MessageBox.Show("Not enough Blue Sky Crystals. ", "Insufficient Currency", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            Random random = new Random();
            int randomNumber = random.Next(1, 101); // Gacha Systems
            _player.AddCurrency(-1600);
            _wishPlayerCurrency.Text = _player.GetSetCurrency.ToString();
            _currentPlayerCurrency.Text = _player.GetSetCurrency.ToString();
            //hide controls
            foreach (Control control in _formControls)
            {
                control.Visible = false;
            }
            string imagePath;
            int displayTime = 8600;
            bool is5star = false;
            if (randomNumber <= pitySystem)
            {
                // Display 5-star image
                imagePath = "homePageResources\\wish\\wish5stars.gif";
                is5star = true;
                pitySystem = 12;
            }
            else
            {
                // Display 4-star image
                imagePath = "homePageResources\\wish\\wish4stars.gif";
                pitySystem += 12;    
            }

            PictureBox gachaAnimation = new PictureBox();
            gachaAnimation.Dock = DockStyle.Fill;
            gachaAnimation.Image = Image.FromFile(imagePath);
            gachaAnimation.SizeMode = PictureBoxSizeMode.StretchImage;
            gachaAnimation.BringToFront();
            this.Controls.Add(gachaAnimation);
            await Task.Delay(displayTime); // Delay for the specified display time
            //bring them here again
            foreach (Control control in _formControls)
            {
                control.Visible = true;
            }
            gachaAnimation.Dispose();
            if (is5star)
            {
                _5StarsGachaSystem gacha5stars = new _5StarsGachaSystem(_player);
                gacha5stars.UpdateInventory();
            }
            else
            {
                _4StarsGachaSystem gacha4stars = new _4StarsGachaSystem(_player);
                gacha4stars.UpdateInventory();
            }
            is5star= false;
        }

        private void DetailsButton_Click(object sender, EventArgs e)
        {
            Form detailsForm = new Form();
            detailsForm.Text = "Wish Event Details";
            detailsForm.Size = new Size(400, 150);

            // Concatenate the rates into a single string
            string ratesText = "Rate of 5-star character: 1.2%" + Environment.NewLine +
                               "Rate of 4-star character: 8.92%" + Environment.NewLine +
                               "Rate of 3-star item: 90.96%";

            // Add a read-only text box to display the rates
            TextBox ratesTextBox = new TextBox();
            ratesTextBox.Multiline = true;
            ratesTextBox.Text = ratesText;
            ratesTextBox.ReadOnly = true;
            ratesTextBox.Location = new Point(20, 20);
            ratesTextBox.Size = new Size(350, 100);
            detailsForm.Controls.Add(ratesTextBox);
            detailsForm.ShowDialog();
        }
    }
}
